#!/bin/bash
set -e -x

datadir=/var/lib/mysql/data

mkdir -p /run/mysqld
chown -R mysql:mysql ${datadir} /run/mysqld

if find ${datadir} -maxdepth 0 -empty | read
then
	firstrun=true
fi

/usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=${datadir}

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-""}
MYSQL_DATABASE=${MYSQL_DATABASE:-""}
MYSQL_USER=${MYSQL_USER:-""}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
MYSQLD_ARGS=${MYSQLD_ARGS:-""}

if [[ ! -z "$firstrun" ]]
then
	tfile=`mktemp`
	if [[ ! -f "$tfile" ]]; then
	    return 1
	fi

	cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
UPDATE user SET password=PASSWORD("$MYSQL_ROOT_PASSWORD") WHERE user='root';
EOF

	if [[ $MYSQL_DATABASE != "" ]]; then
	    echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile

	    if [[ $MYSQL_USER != "" ]]; then
	        echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
	    fi
	fi

	/usr/sbin/mysqld --user=mysql --datadir=${datadir} --bootstrap --verbose=0 $MYSQLD_ARGS < $tfile
	rm -f $tfile
fi

/usr/sbin/mysqld --user=mysql --datadir=${datadir} $MYSQLD_ARGS